services:
  grammar:
    environment:
      - HOST=0.0.0.0
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Binde das gesamte Projektverzeichnis ein, damit Änderungen auf dem Host im Container sichtbar sind
      - .:/app
