/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [{
      type: 'doc',
      id: 'einleitung/index',
      label: 'Einleitung',
    },
    {
      type: 'category',
      label: 'Erste Schritte',
      collapsed: false,
      items: ["erste-schritte/alphabet", "erste-schritte/aussprache", "erste-schritte/rechtschreibung"],
    },
    {
      type: 'category',
      label: 'Wortarten',
      items: [
        "wortarten/substantive/index",
        "wortarten/adjektive/index",
        "wortarten/pronomen/index",
        "wortarten/zahlwoerter/index",
        "wortarten/adverbien/index",
        "wortarten/verben/index",
        "wortarten/partikel/index",
        "wortarten/interjektionen/index",
        "wortarten/praepositionen/index",
        "wortarten/konjunktionen/index",

      ],
    },
    {
      type: 'category',
      label: 'Satzbau',
      items: ["satzbau/index"]
    },
    {
      type: 'category',
      label: 'Hinweise',
      items: ["hinweise/grammatikbegriffe", "hinweise/quellen"]
    },
  ]
};